CC      = gcc
CFLAGS  = -fsanitize=address -ggdb -O0 -std=c99 -D_POSIX_C_SOURCE=200809L

CXX       = g++
CXXFLAGS  = -ggdb -O0 -std=c++17

# PREFIX defined in /make.conf
LDFLAGS = -L$(PREFIX)/lib -lfear
