module = { SOI ~ newline* ~ module_header ~ newline* ~ (function_def | function_decl)* ~ EOI }

module_header = {
  "#" ~ whitespace* ~ "module" ~ whitespace* ~
  "\"" ~ whitespace* ~ ident ~ whitespace* ~ "\"" ~ newline*
}

callconv = { "c" | "sysv" | "msabi" }
linkage  = { "external" | "internal" | "weak" }

function_def = { 
  "__abi" ~ "(" ~ callconv ~ ")" ~ whitespace+ ~ 
  "define" ~ whitespace+ ~ linkage ~ whitespace+ ~ 
  ident ~ "(" ~ whitespace* ~ params? ~ whitespace* ~ ")" ~ whitespace* ~ 
  "->" ~ whitespace* ~ ty ~ whitespace* ~ 
  "{" ~ newline+ ~ block* ~ whitespace* ~ "}" ~ newline*
}

function_decl = {
  "__abi" ~ "(" ~ callconv ~ ")" ~ whitespace+ ~ 
  "declare" ~ whitespace+ ~ linkage ~ whitespace+ ~ 
  ident ~ "(" ~ whitespace* ~ params_decl? ~ whitespace* ~ ")" ~ whitespace* ~ 
  "->" ~ whitespace* ~ ty ~ newline+
}

params      = { param ~ ("," ~ whitespace* ~ param)* }
param       = { value ~ ":" ~ whitespace* ~ ty }
params_decl = { ty ~ ("," ~ whitespace* ~ ty)* }

block = { label ~ (whitespace* ~ "(" ~ params ~ ")")? ~ ":" ~ (whitespace+ ~ entry_marker)? ~ whitespace* ~ newline+ ~ instruction* }
entry_marker = { "__entry__" }

instruction = { whitespace* ~ (assign | plain) ~ whitespace* ~ newline+ }

assign = { value ~ whitespace* ~ "=" ~ whitespace* ~ (call_inst | normal_inst) }
plain  = { jmp_inst | jmpif_inst | call_inst | normal_inst }

jmp_inst   = { "jmp" ~ whitespace+ ~ label ~ ("(" ~ whitespace* ~ pure_args? ~ whitespace* ~ ")")? }
jmpif_inst = { "jmpif" ~ whitespace+ ~ value ~ whitespace+ ~ label_arg ~ "," ~ whitespace* ~ label_arg }
call_inst  = { "call" ~ whitespace+ ~ ident ~ "(" ~ whitespace* ~ pure_args? ~ whitespace* ~ ")" }

normal_inst = { full_opcode ~ (whitespace+ ~ operands)? }

label_arg = { label ~ ("(" ~ whitespace* ~ pure_args? ~ whitespace* ~ ")")? }

pure_args = { value ~ ("," ~ whitespace* ~ value)* }

full_opcode = @{ ( "volatile" ~ whitespace+ )? ~ opcode ~ ( "." ~ (ty | ident) )? }

opcode = { 
  "alloca" | "elemptr" |
  "add" | "sub" | "mul" | "div" | "sdiv" | "udiv" | "rem" | "srem" | "urem" |
  "fadd" | "fsub" | "fmul" | "fdiv" | "frem" |
  "not" | "and" | "or" | "xor" |
  "const" | "cmp" | "fcmp" | "ret" | "lshl" | "lshr" | "ashr" |
  "load" | "store" | "cast"
}

operands = { operand ~ ((whitespace* ~ "," ~ whitespace* | whitespace+) ~ operand)* }
operand  = { ty | cmp_cond | value | label | ident }

cmp_cond = @{ (ASCII_ALPHA | "=" | "<" | ">" | "!")+ }

ty    = { "i8" | "i16" | "i32" | "i64" | "f32" | "f64" | "void" }
value = { ( "%" | "" ) ~ "-"? ~ ASCII_DIGIT+ ~ ( "." ~ ASCII_DIGIT+ )? }
label = { "B" ~ ASCII_DIGIT+ }

whitespace = _{ " " | "\t" | "\r" | "\u{00A0}" }
newline    = _{ "\n" }
ident = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

COMMENT = _{ "!" ~ (!newline ~ ANY)* }