#ifndef __FEAR_H
#define __FEAR_H

/* generated by cbindgen - do not edit */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Fear backend type
 */
typedef enum FearBackend
{
    /**
     * default backend
     */
    FearBackendCranelift,
    /**
     * not yet implemented
     */
    FearBackendSelf,
    FearBackendLlvm,
} FearBackend;

/**
 * Optimization levels mapping directly to compiler backend passes.
 */
typedef enum FearOptLevel
{
    FearOptNone,
    FearOptDefault,
    FearOptFull,
} FearOptLevel;

/**
 * Supported types
 */
typedef enum FearType
{
    FearVoid,
    FearBool,
    FearInt8,
    FearInt16,
    FearInt32,
    FearInt64,
    FearFloat32,
    FearFloat64,
    FearPointer,
} FearType;

/**
 * Integer compare predicate
 */
typedef enum FearIntCmp
{
    FearIntCmpEq,
    FearIntCmpNe,
    FearIntCmpLt,
    FearIntCmpLe,
    FearIntCmpGt,
    FearIntCmpGe,
} FearIntCmp;

/**
 * Float compare predicate
 */
typedef enum FearFloatCmp
{
    FearFloatCmpOrd,
    FearFloatCmpOrdEq,
    FearFloatCmpOrdNe,
    FearFloatCmpOrdLt,
    FearFloatCmpOrdLe,
    FearFloatCmpOrdGt,
    FearFloatCmpOrdGe,
    FearFloatCmpUno,
    FearFloatCmpUnoEq,
    FearFloatCmpUnoNe,
    FearFloatCmpUnoLt,
    FearFloatCmpUnoLe,
    FearFloatCmpUnoGt,
    FearFloatCmpUnoGe,
} FearFloatCmp;

/**
 * Linkage types specifying visibility and resolution rules for symbols.
 */
typedef enum FearLinkage
{
    FearLinkageExternal,
    FearLinkageInternal,
    FearLinkageWeak,
} FearLinkage;

/**
 * Calling conventions supported for function declarations and calls.
 */
typedef enum FearCallConv
{
    FearCallConvC,
    FearCallConvSysV,
    FearCallConvMsAbi,
} FearCallConv;

/**
 * Opaque wrapper for the internal `Module` struct
 */
typedef struct FearModule
{
    int8_t __[0];
} FearModule;

typedef uint32_t FearBlockId;

/**
 * Opaque wrapper for the internal `FunctionDef` struct, used to build
 * function bodies.
 */
typedef struct FearFunctionDef
{
    int8_t __[0];
} FearFunctionDef;

typedef uint32_t FearValueId;

typedef uint32_t FearFuncId;

#ifdef __cplusplus
extern "C"
{
#endif // __cplusplus

    /**
     * Checks if the backend is supported in this library build.
     */
    bool             fearHasBackend(enum FearBackend backend);

    /**
     * Initialising logging system
     */
    int32_t          fearInitialiseLogging(void);

    /**
     * Select any backend
     * Check by fearHasBackend()
     */
    enum FearBackend fearSelectBackend(void);

    /**
     * Select backend for output type object
     * Check by fearHasBackend()
     */
    enum FearBackend fearSelectBackendForObject(void);

    /**
     * Compiles a `FearModule` into a native machine object file via target
     * backend, streaming to a raw file descriptor.
     */
    int  fearEmitObject(struct FearModule *m, enum FearBackend backend,
                        enum FearOptLevel opt, int fd);

    /**
     * Supported backends: FearBackendLlvm
     * Compiles a `FearModule` into a native machine assembly file via
     * target backend, streaming to a raw file descriptor.
     */
    int  fearEmitAssembly(struct FearModule *m, enum FearBackend backend,
                          enum FearOptLevel opt, int fd);

    /**
     * Writes a readable, plain-text representation of the module's IR into
     * a file descriptor.
     */
    void fearDumpToFile(struct FearModule *m, int fd);

    /**
     * Serializes the module into the compiler's native binary format and
     * outputs it to a file descriptor.
     */
    void fearBinaryDumpToFile(struct FearModule *m, int fd);

    /**
     * Creates a new basic block inside the function to build branches or
     * loops.
     */
    FearBlockId fearCreateBlock(struct FearFunctionDef *f);

    /**
     * Adds a top-level input parameter to the function declaration.
     */
    FearBlockId fearCreateFuncParam(struct FearFunctionDef *f,
                                    enum FearType           ty);

    /**
     * Appends a parameter to a specific basic block, used to pass values
     * in SSA form (instead of PHI nodes).
     */
    FearBlockId fearCreateBlockParam(struct FearFunctionDef *f,
                                     FearBlockId block, enum FearType ty);

    /**
     * Generates an integer constant value inside a target basic block.
     */
    FearValueId fearCreateIntConst(struct FearFunctionDef *f,
                                   FearBlockId parent, enum FearType ty,
                                   int64_t val);

    /**
     * Emits an instruction to allocate stack space for a local variable of
     * the specified type.
     */
    FearValueId fearCreateAlloca(struct FearFunctionDef *f,
                                 FearBlockId parent, enum FearType ty);

    /**
     * Emits an instruction to allocate stack space for a local variable of
     * the specified type.
     */
    FearValueId fearCreateArrayAlloca(struct FearFunctionDef *f,
                                      FearBlockId parent, enum FearType ty,
                                      uint32_t count);

    /**
     * Emits an instruction to get a pointer with offset (byte-addressed).
     */
    FearValueId fearCreatePtrOffset(struct FearFunctionDef *f,
                                    FearBlockId parent, FearValueId base,
                                    FearValueId offset);

    /**
     * Emits an instruction to get a pointer with offset
     * (element-addressed).
     */
    FearValueId fearCreateElementPtr(struct FearFunctionDef *f,
                                     FearBlockId parent, enum FearType ty,
                                     FearValueId base, FearValueId offset);

    /**
     * Emits an instruction to load a value of type `ty` from a memory
     * address pointed to by `ptr`.
     */
    FearValueId fearCreateLoad(struct FearFunctionDef *f,
                               FearBlockId parent, enum FearType ty,
                               FearValueId ptr);

    /**
     * Emits an instruction to store a `value` into a memory address
     * specified by `ptr`.
     */
    void fearCreateStore(struct FearFunctionDef *f, FearBlockId parent,
                         FearValueId ptr, FearValueId value);

    /**
     * Emits a volatile load instruction, ensuring memory access is not
     * optimized away or reordered.
     */
    FearValueId fearCreateVolatileLoad(struct FearFunctionDef *f,
                                       FearBlockId             parent,
                                       enum FearType ty, FearValueId ptr);

    /**
     * Emits a volatile store instruction, ensuring the memory write occurs
     * exactly as requested.
     */
    void fearCreateVolatileStore(struct FearFunctionDef *f,
                                 FearBlockId parent, FearValueId ptr,
                                 FearValueId value);

    /**
     * Appends a function call instruction to a basic block with an array
     * of argument identifiers.
     */
    FearValueId fearCreateCall(struct FearFunctionDef *f,
                               FearBlockId parent, FearFuncId func,
                               enum FearType ty, const FearValueId *args,
                               uint32_t nargs);

    FearValueId fearCreateAdd(struct FearFunctionDef *f,
                              FearBlockId parent, enum FearType ty,
                              FearValueId a, FearValueId b);

    FearValueId fearCreateSub(struct FearFunctionDef *f,
                              FearBlockId parent, enum FearType ty,
                              FearValueId a, FearValueId b);

    FearValueId fearCreateMul(struct FearFunctionDef *f,
                              FearBlockId parent, enum FearType ty,
                              FearValueId a, FearValueId b);

    FearValueId fearCreateDiv(struct FearFunctionDef *f,
                              FearBlockId parent, enum FearType ty,
                              FearValueId a, FearValueId b);

    FearValueId fearCreateUnsignedDiv(struct FearFunctionDef *f,
                                      FearBlockId parent, enum FearType ty,
                                      FearValueId a, FearValueId b);

    FearValueId fearCreateRem(struct FearFunctionDef *f,
                              FearBlockId parent, enum FearType ty,
                              FearValueId a, FearValueId b);

    FearValueId fearCreateUnsignedRem(struct FearFunctionDef *f,
                                      FearBlockId parent, enum FearType ty,
                                      FearValueId a, FearValueId b);

    FearValueId fearCreateFloatAdd(struct FearFunctionDef *f,
                                   FearBlockId parent, enum FearType ty,
                                   FearValueId a, FearValueId b);

    FearValueId fearCreateFloatSub(struct FearFunctionDef *f,
                                   FearBlockId parent, enum FearType ty,
                                   FearValueId a, FearValueId b);

    FearValueId fearCreateFloatMul(struct FearFunctionDef *f,
                                   FearBlockId parent, enum FearType ty,
                                   FearValueId a, FearValueId b);

    FearValueId fearCreateFloatDiv(struct FearFunctionDef *f,
                                   FearBlockId parent, enum FearType ty,
                                   FearValueId a, FearValueId b);

    FearValueId fearCreateFloatRem(struct FearFunctionDef *f,
                                   FearBlockId parent, enum FearType ty,
                                   FearValueId a, FearValueId b);

    FearValueId fearCreateBitwiseNot(struct FearFunctionDef *f,
                                     FearBlockId parent, enum FearType ty,
                                     FearValueId v);

    FearValueId fearCreateBitwiseAnd(struct FearFunctionDef *f,
                                     FearBlockId parent, enum FearType ty,
                                     FearValueId a, FearValueId b);

    FearValueId fearCreateBitwiseOr(struct FearFunctionDef *f,
                                    FearBlockId parent, enum FearType ty,
                                    FearValueId a, FearValueId b);

    FearValueId fearCreateBitwiseXor(struct FearFunctionDef *f,
                                     FearBlockId parent, enum FearType ty,
                                     FearValueId a, FearValueId b);

    FearValueId fearCreateLogicalShiftLeft(struct FearFunctionDef *f,
                                           FearBlockId             parent,
                                           enum FearType ty, FearValueId a,
                                           FearValueId b);

    FearValueId fearCreateLogicalShiftRight(struct FearFunctionDef *f,
                                            FearBlockId             parent,
                                            enum FearType           ty,
                                            FearValueId a, FearValueId b);

    FearValueId fearCreateArithShiftRight(struct FearFunctionDef *f,
                                          FearBlockId             parent,
                                          enum FearType ty, FearValueId a,
                                          FearValueId b);

    /**
     * Terminates a block with an unconditional jump to another basic
     * block, passing arguments to its block parameters.
     */
    void fearCreateJump(struct FearFunctionDef *f, FearBlockId parent,
                        FearBlockId target, const FearValueId *params,
                        uint32_t nparams);

    /**
     * Compares two integers
     */
    FearValueId fearCreateIntCompare(struct FearFunctionDef *f,
                                     FearBlockId             parent,
                                     enum FearIntCmp pred, FearValueId lhs,
                                     FearValueId rhs);

    /**
     * Compares two floatpoint values
     */
    FearValueId fearCreateFloatCompare(struct FearFunctionDef *f,
                                       FearBlockId             parent,
                                       enum FearFloatCmp       pred,
                                       FearValueId lhs, FearValueId rhs);

    /**
     * Emits an instruction to zero-extend an integer to a wider integer
     * type.
     */
    FearValueId fearCreateZeroExt(struct FearFunctionDef *f,
                                  FearBlockId parent, enum FearType ty,
                                  FearValueId src);

    /**
     * Emits an instruction to sign-extend an integer to a wider integer
     * type.
     */
    FearValueId fearCreateSignExt(struct FearFunctionDef *f,
                                  FearBlockId parent, enum FearType ty,
                                  FearValueId src);

    /**
     * Emits an instruction to truncate an integer to a narrower integer
     * type.
     */
    FearValueId fearCreateTrunc(struct FearFunctionDef *f,
                                FearBlockId parent, enum FearType ty,
                                FearValueId src);

    /**
     * Emits an instruction to bitcast a value to another type of the same
     * bit width without changing the raw bits.
     */
    FearValueId fearCreateBitcast(struct FearFunctionDef *f,
                                  FearBlockId parent, enum FearType ty,
                                  FearValueId src);

    /**
     * Emits an instruction to convert a signed integer to a floating-point
     * value.
     */
    FearValueId fearCreateIntToFloat(struct FearFunctionDef *f,
                                     FearBlockId parent, enum FearType ty,
                                     FearValueId src);

    /**
     * Emits an instruction to convert an unsigned integer to a
     * floating-point value.
     */
    FearValueId fearCreateUnsignedIntToFloat(struct FearFunctionDef *f,
                                             FearBlockId   parent,
                                             enum FearType ty,
                                             FearValueId   src);

    /**
     * Emits an instruction to convert a floating-point value to a signed
     * integer.
     */
    FearValueId fearCreateFloatToInt(struct FearFunctionDef *f,
                                     FearBlockId parent, enum FearType ty,
                                     FearValueId src);

    /**
     * Emits an instruction to convert a floating-point value to an
     * unsigned integer.
     */
    FearValueId fearCreateFloatToUnsignedInt(struct FearFunctionDef *f,
                                             FearBlockId   parent,
                                             enum FearType ty,
                                             FearValueId   src);

    /**
     * Emits an instruction to extend a floating-point value to a higher
     * precision floating-point type (e.g., f32 to f64).
     */
    FearValueId fearCreateFloatPromote(struct FearFunctionDef *f,
                                       FearBlockId             parent,
                                       enum FearType ty, FearValueId src);

    /**
     * Emits an instruction to truncate a floating-point value to a lower
     * precision floating-point type (e.g., f64 to f32).
     */
    FearValueId fearCreateFloatTrunc(struct FearFunctionDef *f,
                                     FearBlockId parent, enum FearType ty,
                                     FearValueId src);

    /**
     * Terminates a block with a conditional jump. Switches control flow to
     * block `t` (true) or `e` (false) depending on `cond`.
     */
    void fearCreateCondJump(struct FearFunctionDef *f, FearBlockId parent,
                            FearValueId cond, FearBlockId t,
                            const FearValueId *targs, uint32_t tn,
                            FearBlockId e, const FearValueId *eargs,
                            uint32_t en);

    /**
     * Terminates a block with a return instruction passing a return value.
     */
    void fearCreateRet(struct FearFunctionDef *f, FearBlockId parent,
                       FearValueId v);

    /**
     * Terminates a block with a void return instruction.
     */
    void fearCreateRetVoid(struct FearFunctionDef *f, FearBlockId parent);

    /**
     * Declares a function prototype inside the module. Returns a unique
     * function identifier.
     */
    FearFuncId fearDeclareFunction(struct FearModule *m, const char *name,
                                   const enum FearType *params,
                                   uint32_t nparams, enum FearType returns,
                                   enum FearLinkage linkage);

    /**
     * Modifies the calling convention of a previously declared function.
     */
    void       fearFunctionSetCC(struct FearModule *m, FearFuncId id,
                                 enum FearCallConv cc);

    /**
     * Allocates an empty `FunctionDef` on the heap to start building an
     * SSA function body.
     */
    struct FearFunctionDef *fearDefinitionCreate(void);

    /**
     * Deallocates a `FunctionDef` from heap memory if it wasn't consumed
     * by `fearDefineFunction`.
     */
    void        fearDefinitionDispose(struct FearFunctionDef *f);

    /**
     * Binds a complete function definition (cloned) (`FunctionDef`) to a
     * declared function ID within the module.
     */
    void        fearDefineFunction(struct FearModule *m, FearFuncId id,
                                   const struct FearFunctionDef *def);

    /**
     * Gets the identifier of the entry basic block automatically created
     * for a function definition.
     */
    FearBlockId fearGetEntryBlock(struct FearFunctionDef *f);

    /**
     * Sets the identifier of the entry basic block.
     */
    void fearSetEntryBlock(struct FearFunctionDef *f, FearBlockId block);

    /**
     * Allocates a new empty `Module` on the heap and returns its raw
     * pointer. Ownership is transferred to C.
     */
    struct FearModule *fearModuleCreate(const char *name);

    /**
     * Deserializes a complete `Module` structure from an input file
     * descriptor. Returns null on error.
     */
    struct FearModule *fearReadBinaryFromFile(int fd);

    /**
     * Reclaims ownership of a `FearModule` pointer and drops it, freeing
     * all associated heap memory.
     */
    void               fearModuleDispose(struct FearModule *m);

    /**
     * Runs internal optimization passes (e.g., dead code elimination,
     * simplification) over the module's IR. Return total passes count
     */
    uint32_t           fearModuleOptimize(struct FearModule *m,
                                          enum FearOptLevel  level);

    /**
     * Runs internal optimization passes (e.g., dead code elimination,
     * simplification) over the module's IR. Uses multilevel pipeline
     * Return total passes count (exclude multilevel passes)
     */
    uint32_t fearModuleOptimizeMultilevel(struct FearModule *m,
                                          enum FearOptLevel  level);

    /**
     * Verify module
     * Return verify errors count.
     */
    uint32_t fearModuleVerify(struct FearModule *m);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* __FEAR_H */
