#ifndef __FEAR_C_H
#define __FEAR_C_H

/* generated by cbindgen - do not edit */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum FearOptLevel {
  FearOptNone,
  FearOptDefault,
  FearOptFull,
} FearOptLevel;

typedef enum FearType {
  FearVoid,
  FearBool,
  FearInt8,
  FearInt16,
  FearInt32,
  FearInt64,
  FearFloat32,
  FearFloat64,
  FearPointer,
} FearType;

/**
 * opaque
 */
typedef struct FearModule {
  int8_t __[0];
} FearModule;

typedef uint32_t FearFuncId;

/**
 * opaque
 */
typedef struct FearFunctionDef {
  int8_t __[0];
} FearFunctionDef;

typedef uint32_t FearBlockId;

typedef uint32_t FearValueId;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

bool fearLoweringHasLLVM(void);

bool fearLoweringHasCranelift(void);

void fearEmitCraneliftObjectToFile(struct FearModule *m, enum FearOptLevel opt, int fd);

struct FearModule *fearModuleCreate(const char *name);

struct FearModule *fearBinaryFetchModuleFromFile(int fd);

void fearModuleDispose(struct FearModule *m);

void fearModuleOptimize(struct FearModule *m);

void fearDumpToStringBuffer(struct FearModule *m, char *buf, uint32_t len);

void fearDumpToFile(struct FearModule *m, int fd);

void fearBinaryDumpToFile(struct FearModule *m, int fd);

FearFuncId fearDeclareFunction(struct FearModule *m,
                               const char *name,
                               const enum FearType *params,
                               uint32_t nparams,
                               enum FearType returns);

struct FearFunctionDef *fearDefinitionCreate(void);

void fearDefinitionDispose(struct FearFunctionDef *f);

void fearDefineFunction(struct FearModule *m, FearFuncId id, const struct FearFunctionDef *def);

FearBlockId fearGetEntryBlock(struct FearFunctionDef *f);

FearBlockId fearCreateBlock(struct FearFunctionDef *f);

FearBlockId fearCreateFuncParam(struct FearFunctionDef *f, enum FearType ty);

FearBlockId fearCreateBlockParam(struct FearFunctionDef *f, FearBlockId block, enum FearType ty);

FearValueId fearCreateIntConst(struct FearFunctionDef *f,
                               FearBlockId parent,
                               enum FearType ty,
                               int64_t val);

FearValueId fearCreateAdd(struct FearFunctionDef *f,
                          FearBlockId parent,
                          enum FearType ty,
                          FearValueId a,
                          FearValueId b);

FearValueId fearCreateSub(struct FearFunctionDef *f,
                          FearBlockId parent,
                          enum FearType ty,
                          FearValueId a,
                          FearValueId b);

FearValueId fearCreateMul(struct FearFunctionDef *f,
                          FearBlockId parent,
                          enum FearType ty,
                          FearValueId a,
                          FearValueId b);

FearValueId fearCreateSignedDiv(struct FearFunctionDef *f,
                                FearBlockId parent,
                                enum FearType ty,
                                FearValueId a,
                                FearValueId b);

FearValueId fearCreateUnsignedDiv(struct FearFunctionDef *f,
                                  FearBlockId parent,
                                  enum FearType ty,
                                  FearValueId a,
                                  FearValueId b);

FearValueId fearCreateSignedRem(struct FearFunctionDef *f,
                                FearBlockId parent,
                                enum FearType ty,
                                FearValueId a,
                                FearValueId b);

FearValueId fearCreateUnsignedRem(struct FearFunctionDef *f,
                                  FearBlockId parent,
                                  enum FearType ty,
                                  FearValueId a,
                                  FearValueId b);

FearValueId fearCreateFloatAdd(struct FearFunctionDef *f,
                               FearBlockId parent,
                               enum FearType ty,
                               FearValueId a,
                               FearValueId b);

FearValueId fearCreateFloatSub(struct FearFunctionDef *f,
                               FearBlockId parent,
                               enum FearType ty,
                               FearValueId a,
                               FearValueId b);

FearValueId fearCreateFloatMul(struct FearFunctionDef *f,
                               FearBlockId parent,
                               enum FearType ty,
                               FearValueId a,
                               FearValueId b);

FearValueId fearCreateFloatDiv(struct FearFunctionDef *f,
                               FearBlockId parent,
                               enum FearType ty,
                               FearValueId a,
                               FearValueId b);

FearValueId fearCreateFloatRem(struct FearFunctionDef *f,
                               FearBlockId parent,
                               enum FearType ty,
                               FearValueId a,
                               FearValueId b);

FearValueId fearCreateBitwiseNot(struct FearFunctionDef *f,
                                 FearBlockId parent,
                                 enum FearType ty,
                                 FearValueId v);

FearValueId fearCreateBitwiseAnd(struct FearFunctionDef *f,
                                 FearBlockId parent,
                                 enum FearType ty,
                                 FearValueId a,
                                 FearValueId b);

FearValueId fearCreateBitwiseOr(struct FearFunctionDef *f,
                                FearBlockId parent,
                                enum FearType ty,
                                FearValueId a,
                                FearValueId b);

FearValueId fearCreateBitwiseXor(struct FearFunctionDef *f,
                                 FearBlockId parent,
                                 enum FearType ty,
                                 FearValueId a,
                                 FearValueId b);

FearValueId fearCreateLogicalShiftLeft(struct FearFunctionDef *f,
                                       FearBlockId parent,
                                       enum FearType ty,
                                       FearValueId a,
                                       FearValueId b);

FearValueId fearCreateLogicalShiftRight(struct FearFunctionDef *f,
                                        FearBlockId parent,
                                        enum FearType ty,
                                        FearValueId a,
                                        FearValueId b);

FearValueId fearCreateArithShiftRight(struct FearFunctionDef *f,
                                      FearBlockId parent,
                                      enum FearType ty,
                                      FearValueId a,
                                      FearValueId b);

void fearCreateJump(struct FearFunctionDef *f,
                    FearBlockId parent,
                    FearBlockId target,
                    const FearValueId *params,
                    uint32_t nparams);

void fearCreateCondJump(struct FearFunctionDef *f,
                        FearBlockId parent,
                        FearValueId cond,
                        FearBlockId t,
                        const FearValueId *targs,
                        uint32_t tn,
                        FearBlockId e,
                        const FearValueId *eargs,
                        uint32_t en);

void fearCreateRet(struct FearFunctionDef *f, FearBlockId parent, FearValueId v);

void fearCreateRetVoid(struct FearFunctionDef *f, FearBlockId parent);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* __FEAR_C_H */
